### ISSUE TITLE
Create page for increasing inbound capacity

### ISSUE THREAD

**Issue by MoritzKa** [getAlby/hub#112]
We have a general flow to open a channel ([Figma](https://www.figma.com/design/2IyilDewDrdNP3G1NixPYd/Alby-Hub?node-id=2135-84835&t=QdqeiHdgRjrcFoEH-4)). But it does not yet differentiate for the user between increasing inbound and increasing outbound. 

We also want to integrate different LSPs to buy inbound liquidity according to the LSPS1 spec: https://github.com/BitcoinAndLightningLayerSpecs/lsp/tree/main/LSPS1

A very first step could be to add a "Increase Receiving Capacity" button to the wallet view of the Hub and link to [this page](https://guides.getalby.com/user-guide/v/alby-account-and-browser-extension/alby-hub/liquidity/increase-receiving-capacity)

A second step could be a page in the Hub that lets the user set:
1. Funding Method (bitcoin/lightning)
2. Receiving Capacity in sats
3. Spending Balance in sats
4. Funding Method (bitcoin/lightning)
5. time in weeks the channel remains open
6. set private/public
7. channel peer
8. show invoice/ deposit address

Blocktank's widget is a great inspiration. Feel free to refine.

**Comment by stackingsaunter** [comment]
I think this can be closed with the new design and a version with those two inputs seperated @MoritzKa
