### ISSUE TITLE
Clouds not showing in onboarding any more (only when system appearance = light mode)

### ISSUE THREAD

**Issue by rolznz** [getAlby/hub#221]
to reproduce, delete your cookies/local storage and set system appearance to lightmode. Then go through the onboarding.

**Comment by bumi** [comment]
this also broke? 
![CleanShot 2024-07-08 at 10 01 14@2x](https://github.com/getAlby/hub/assets/318/c99d25ea-66db-4229-9e4c-8edd8fd681d8)

**Comment by bumi** [comment]
I think the default theme is not chosen

**Comment by rolznz** [comment]
Jakub said he'd be ok if we can find a way to force the app to use dark mode just on the onboarding pages
