### ISSUE TITLE
"Transfer" button shows "not enough balance" error message

### ISSUE THREAD

**Issue by MoritzKa** [getAlby/hub#238]
- A user bought incoming liquidity from an LSP
- Then connected the Alby Account to the Hub
- Then tried to click "Transfer" of the Alby Hosted Balance. But Alby Hub shows: "not enough balance. Make sure you have at least 1% reserved for potential fees"

**Comment by rolznz** [comment]
I think @reneaaron found the issue in https://github.com/getAlby/hub/pull/235 :crossed_fingers:
