### ISSUE TITLE
Link Guides 

### ISSUE THREAD

**Issue by MoritzKa** [getAlby/hub#288]
There very guides and we need to get users to read them more.  What about an item with "Hub Guides" or "Guides"
Link: https://guides.getalby.com/user-guide/v/alby-account-and-browser-extension/alby-hub
![image](https://github.com/user-attachments/assets/4932773b-ec86-49af-a8cf-d46e8cb5a4ee)

**Comment by rolznz** [comment]
I was wrong, I thought this was done already. Sorry!
