### ISSUE TITLE
Fix: onboarding tasklist order

### ISSUE THREAD

**Issue by itstomekk** [getAlby/hub#309]
![image](https://github.com/user-attachments/assets/1f3efbda-d65e-41e6-8290-d024c9111d32)
 1.4.5.2.3

**Comment by rolznz** [comment]
This is actually the intended order because you did steps out of order. CC @reneaaron

**Comment by reneaaron** [comment]
I agree it feels strange, PR: https://github.com/getAlby/hub/pull/314
