### ISSUE TITLE
Send 80% budget usage warning event

### ISSUE THREAD

**Issue by bumi** [getAlby/hub#319]
Currently the experience is pretty bad when a budget is used. 
Can we send an event and notify the user via email if for example 80% of the budget is used?

**Comment by rolznz** [comment]
Should we also have one for 50%?

So the user would (hopefully) get 2 notifications before they receive the permission denied notification

**Comment by bumi** [comment]
not sure what good numbers are.

**Comment by rolznz** [comment]
We currently don't - the `nwc_payment_succeeded` and `nwc_payment_failed` events are being sent from the NWC controllers and we do the budget check in another layer (the transactions service).

The easiest way would be to fire a new event from the transactions service every time we validate the balance/budget. I'm not sure if this is a good idea though?
