### ISSUE TITLE
Bitcoin Connect: Wrong colors used in light mode

### ISSUE THREAD

**Issue by reneaaron** [getAlby/hub#329]
![image](https://github.com/user-attachments/assets/f358bcdd-48cf-4e55-9746-a41b55d25d29)

System setting: dark
Hub theme: default, light

**Comment by rolznz** [comment]
This is quite an edge case - maybe it's better to remove bitcoin connect though since it doesn't quite fit with the hub

**Comment by rolznz** [comment]
Remove bitcoin connect instead
