### ISSUE TITLE
"Last used" missing on some cards

### ISSUE THREAD

**Issue by rolznz** [getAlby/hub#345]
![image](https://github.com/user-attachments/assets/022d7a45-c848-4b1c-9988-667ac2b7ce77)

**Comment by reneaaron** [comment]
@rolznz We don't show it when the app hasn't been used before.

https://github.com/getAlby/hub/blob/master/frontend/src/components/connections/AppCardConnectionInfo.tsx#L81

Do you think we should always show it?

**Comment by rolznz** [comment]
@reneaaron In my opinion it would be good to always show, until we have a better method of dealing with unused connections
