### ISSUE TITLE
Move payment events to transactions service

### ISSUE THREAD

**Issue by rolznz** [getAlby/hub#350]
The `payment_sent` event is async and is confusing with the other `payment_succeeded` which is then consumed by different places around the app. (For example NIP-47 notifications)

The succeeded and failed ones are synchronous, I should have named the sent one better - maybe `payment_succeeded_async` instead of `payment_sent` which would then match the existing `payment_failed_async` one.

**Comment by bumi** [comment]
what was the difference between the sync and the async thing there?

**Comment by rolznz** [comment]
the NWC pay_invoice event has a 60 second timeout, so the request could fail due to timeout (leading to `payment_failed`), but later succeed (leading to `payment_sent`)

**Comment by bumi** [comment]
can we rename it? or does _async describe this enough?

**Comment by rolznz** [comment]
@bumi I would propose this naming - there is only one change:
- `payment_succeeded`
- `payment_succeeded_async` (Renamed from `payment_sent`)
- `payment_failed`
- `payment_failed_async`

**Comment by bumi** [comment]
how about `_later` instead of async? 
or `payment_succeeded_request` and `payment_succeeded_delayed` ?

**Comment by rolznz** [comment]
@bumi it's not necessarily later - we subscribe to LDK/LND events and it will be fired as soon as we get it (which unless the payment is delayed, it will actually be fired before `payment_succeeded`)

**Comment by bumi** [comment]
then maybe we just use that one and not two events? 
sounds like the one is reliable and the other one is not?

**Comment by rolznz** [comment]
@bumi good point, however it'll only work for the LNClients that support notifications. I would actually then move these events to the new transactions service layer which is where our internal database is updated. This will also enable notifications for self payments. (briefly mentioned in https://github.com/getAlby/hub/issues/299)

**Comment by rolznz** [comment]
Also, this will enable self payments for keysend payments which currently relies on the LNClient nwc_payment_received event.
