### ISSUE TITLE
Restore backup on Mac Desktop does not work

### ISSUE THREAD

**Issue by rolznz** [getAlby/hub#391]
![image](https://github.com/user-attachments/assets/14732acc-d278-404f-93db-d3758bc760d6)

**Comment by rolznz** [comment]
> Looking at the file, Hub is exporting a 0-byte file.

**Comment by jpl-btc** [comment]
Does this means the migration on MAC is working again? If so I will notify some users that wanted to execute their migration on MAC. thanks for letting me know

**Comment by rolznz** [comment]
This will go out in the next release.

**Comment by rolznz** [comment]
@im-adithya I got a report that this is not fixed - how did you test it on mac?

**Comment by rolznz** [comment]
cannot reproduce, closing for now. Server build + fixed fetching of logs in the Wails app in 1.7.0 will help us to debug this further

**Comment by bumi** [comment]
I can reproduce this on 1.6.0 on the Mac. this is still the case.
