### ISSUE TITLE
Better error handling on setup

### ISSUE THREAD

**Issue by bumi** [getAlby/hub#396]
what happens when invalid data is entered or when the requests fail. 
We have to make sure it can be retried.

**Comment by rolznz** [comment]
@bumi can you add some more context? this is when the user uses a different node type or advanced setup, right?

**Comment by bumi** [comment]
yes. I kept it open because I think we should review all error cases. 

so for example if the internet connection is not working then I am stuck. it says I already did the setup when I retry.

**Comment by rolznz** [comment]
> so for example if the internet connection is not working then I am stuck. it says I already did the setup when I retry.

Note: this is a protection mechanism against not allowing a user's node setup to be overwritten. (maybe the node should be able to be setup again if the node has never been successfully started)

**Comment by rolznz** [comment]
From ek:
> I subscribed to Alby Hub and I think trying to connect to a local node using "localhost" broke it (wanted to see if it would work). After I was done waiting for it to connect, I clicked "back" and tried to use a Cashu mint but then it said "Setup already finished".
