### ISSUE TITLE
Shadcn tooltips to do not work on mobile

### ISSUE THREAD

**Issue by rolznz** [getAlby/hub#399]
They suggest to use popovers instead, but @stackingsaunter was not really happy with tooltips in the first place. Can we do better?

**Comment by stackingsaunter** [comment]
Let's add those [hybrid tooltips](https://github.com/shadcn-ui/ui/issues/2402#issuecomment-1930895113) please.

If it's not possible or very hard, can we maybe at least hide tooltips on mobile?
