### ISSUE TITLE
Breadcrumbs for peers and sign message

### ISSUE THREAD

**Issue by im-adithya** [getAlby/hub#449]
Peers has no breadcrumbs, we can add it to channels to show "Node" > Peers but is it okay to have the link as `/#/channels/peers`?

<img width="100%" alt="Screenshot 2024-08-12 at 2 23 21 PM" src="https://github.com/user-attachments/assets/8518673d-e43f-4d70-b4bf-7b61fda4f6bc">

Sign Message has wrong breadcrumbs, but it is the same issue again, if we wish to show Node instead of Wallet, we would have the link as `/#/channels/sign-message`

<img width="100%" alt="Screenshot 2024-08-12 at 2 21 19 PM" src="https://github.com/user-attachments/assets/ab10b19a-f659-4a70-94fc-6dfc9a7a3a98">

**Comment by im-adithya** [comment]
Needs input from @rolznz @stackingsaunter

**Comment by rolznz** [comment]
I think they should be both Home -> Node -> ...

We can't easily change the routes. I think that's ok for now
