### ISSUE TITLE
[Feature request] Multi-tenancy for spending BTC (?)

### ISSUE THREAD

**Issue by igorbastosib** [getAlby/hub#454]
I'd like to suggest a multi-tenancy feature while spending BTC, how does it work?

N (**random number** of) Alby or NOSTR accounts are linked to an Alby Account (AlbyA), the receiving process keeps the same. Only while spending BTC from this AlbyA it is need N or N-x signatures/permissions.
In my perfect world it could work somehow with NOSTR keys, so only one Alby account would be necessary, and all N permissions made from the NOSTR keys.

Context:
A Company, with N partners, want to integrate Lightning as payment method with Alby. 
The Alby Account should allow receiving BTCs through LN as expected, but the send/spending process should be allowed only when all N or N-x partners allow the transaction.

**Comment by rolznz** [comment]
Hi,

Unfortunately this is not possible with our lightning implementation or Alby Hub's current architecture.

I believe the simplest option would be to use onchain currently. And also it's such a hassle to get N signatures, onchain is probably ok.

**Comment by igorbastosib** [comment]
It's a pity to hear, but ok...
Thanks for your time.
