### ISSUE TITLE
Return app ID in create app response

### ISSUE THREAD

**Issue by rolznz** [getAlby/hub#460]
Currently you need to do another call to fetch the app by pubkey to get it

**Comment by rolznz** [comment]
@im-adithya sorry, I mean in the HTTP API response. It's not there

**Comment by im-adithya** [comment]
Yeah I got that, but I was talking about this part:

> you need to do another call to fetch the app by pubkey to get it 

We don't seem to use the app id anywhere right (from `createAppResponse` passed in the state)? And we have to keep polling there anyway to check the lastevent in created screen

**Comment by rolznz** [comment]
The app ID is now used for custodial keysends (696969 record)
