### ISSUE TITLE
Paying a phoenixd invoice fails

### ISSUE THREAD

**Issue by greenart7c3** [getAlby/hub#462]
Try to pay a invoice that was created using the createinvoice route from phoenixd and it fails

**Comment by bumi** [comment]
Do you already have enough sats received? or is that all still part of the fee credit. 
this is special to phoenixd: 
https://phoenix.acinq.co/server/auto-liquidity#auto-liquidity

**Comment by greenart7c3** [comment]
Tested sending it again and now it worked. Thank you
