### ISSUE TITLE
Add version number to release artifacts

### ISSUE THREAD

**Issue by rolznz** [getAlby/hub#466]
- If you download multiple versions you end up getting (1), (2) on the files (unless you delete the old ones).
- It's hard to know what version you last downloaded

**Comment by im-adithya** [comment]
We can also do similarly for backups, there we should also change from `nwc.bkp` to something like `alby_hub_v1_5_2.bkp`

**Comment by bumi** [comment]
for me this is a bit of a made up case. what use case is that a user downloads multiple versions at the same time? I think this causes more problems than it does good.

**Comment by rolznz** [comment]
Yeah, I did not expect all the impacts this would cause. I'll close this issue. Thanks!
