### ISSUE TITLE
Improve "Alby Account" budget card

### ISSUE THREAD

**Issue by stackingsaunter** [getAlby/hub#474]
- add a simple CTA for explainer popup
- improve budget layout/copy

[Related UX issue](https://www.notion.so/getalby/Alby-Account-budget-is-not-understood-59f6497380424d83b01d5f5a93567fe3?pvs=4)

**Comment by stackingsaunter** [comment]
![image](https://github.com/user-attachments/assets/73f99380-f7c3-4ac4-ab4a-13eb7105d3da)

![image](https://github.com/user-attachments/assets/5001e7c8-c545-4bb2-91ed-15c731f19fa4)

Current popup with explainer can show up on clicking the tooltip icon. There's CTA there that leads to "Edit budget" screen, same as when clicking on "Edit" icon in the budget itself, but then there's no explainer inside.

Thoughts? @rolznz @reneaaron

**Comment by rolznz** [comment]
What about this popup always shows when you click the edit button on the card? (same as it does when re-linking?)

**Comment by stackingsaunter** [comment]
Can be, but then tooltip feels kinda redundant and would also trigger edit?

**Comment by stackingsaunter** [comment]
@rolznz could we add the tooltip and changed copy to "Left in Alby Account budget"?

Right now I don't see a way to access this explainer at all in Hub
