### ISSUE TITLE
Include Alby hosted balance in the UI

### ISSUE THREAD

**Issue by stackingsaunter** [getAlby/hub#475]
Places to add:

- Onboarding carousel
- Wallet balance

[Related UX issue](https://www.notion.so/getalby/Some-users-think-they-loose-sats-when-launching-Hub-549182d5544849e087589b57b688d8bc?pvs=4)

**Comment by stackingsaunter** [comment]
![image](https://github.com/user-attachments/assets/6f09c083-1ec0-426b-98f6-77e14539cea9)

![image](https://github.com/user-attachments/assets/46198809-e1ea-45d0-a9aa-6e4a6196a902)


WDYT? @rolznz @bumi 
Wallet here would display custodial balance before it's migrated. Some users were thinking funds are gone when they saw 0 here

**Comment by rolznz** [comment]
CC @reneaaron

**Comment by rolznz** [comment]
I like the onboarding slide. I'm not sure about the wallet page, and this depends on them having a channel with incoming liquidity.

**Comment by stackingsaunter** [comment]
>  this depends on them having a channel with incoming liquidity.

What do you mean? Doesn't that display before they have any channels?

**Comment by rolznz** [comment]
@stackingsaunter that only works if you have enough to pay to open a channel (but it's step 1 of the onboarding.)

Do you mean if they don't do step 1 and go immediately to the wallet?

**Comment by stackingsaunter** [comment]
Yeah I meant situation before any migration If they enter Wallet page

**Comment by rolznz** [comment]
another user found it hard to find on the node page. This issue probably fixes it.

**Comment by bumi** [comment]
I like the idea of adding it to the wallet page if the user has a old balance.

**Comment by rolznz** [comment]
"Migrate Funds" button on Wallet page can just go back to the first channel flow.
