### ISSUE TITLE
Make Alby Account Optional

### ISSUE THREAD

**Issue by rolznz** [getAlby/hub#484]
A lot of Alby features will be lost (lightning address, notifications, SCB, auto-channel on onboarding, etc), however privacy-concious users and Start9 would like this.

**Comment by rolznz** [comment]
@bumi I'm not sure about doing this step by step as we talked about - I think it makes sense for a user to choose this configuration at startup otherwise events will still be sent for a short period, which the user may not want, and they're still required to login.

As you said, this can also be controlled by an environment variable, which can be disabled by default on Start9.

**Comment by bumi** [comment]
> choose this configuration at startup otherwise events will still be sent for a short period, which the user may not want, and they're still required to login.

I don't think this is a problem or a good reason not to offer configuration options in the settings.
