### ISSUE TITLE
App Detail Pages

### ISSUE THREAD

**Issue by rolznz** [getAlby/hub#489]
Pages that contributors can create in a folder which will show on specific route. A simple react component that has access to the hub's internal API.

Requirements:
- The react component
- Info (Name, image etc) which need to be exported and can be shown from the app store

Ideas:
- Standard pages (e.g. info and instructions on how to use specific external apps, like Damus, Primal, or Geyser)
- Advanced pages
  - Specific logic for Alby Extension to connect (possibly using window.alby for example?)
- "Plugin" pages
  - Onboard your friends/family with isolated apps page
  - A developer plugin which people can use as a base to make their own
  - ?

**Comment by stackingsaunter** [comment]
Related https://github.com/getAlby/hub/issues/473

**Comment by rolznz** [comment]
Update: for https://github.com/getAlby/hub/issues/473 it might be easier to add custom description/guides to the existing pages for those apps, as they are not "special" - they just need better instructions on how to get started
