### ISSUE TITLE
Add Alby Hub logo to quotes pages

### ISSUE THREAD

**Issue by stackingsaunter** [getAlby/hub#498]
Instead of "Hub", there should be a logo with contrasting color

![image](https://github.com/user-attachments/assets/6616fb8b-e7bd-4179-8f62-b420fafdd989)

**Comment by rolznz** [comment]
I don't understand, do you mean to remove the text "Alby Hub" from the logo?

**Comment by rolznz** [comment]
It looks like this already:
![image](https://github.com/user-attachments/assets/9239bb3f-053e-4bdb-aa81-0acde23735e5)
