### ISSUE TITLE
Redeem funds does not work

### ISSUE THREAD

**Issue by rolznz** [getAlby/hub#504]
See https://github.com/getAlby/hub/pull/363

This doesn't work if there are no channels open, because we do not set aside funds to pay the onchain transaction fee.

Also, it would also drain all the anchor reserves if used multiple times (even just once could decrease anchor reserves which may make it difficult to force close a channel).

**Comment by jpl-btc** [comment]
I have seen this issue 3 or 4 times already. For the moment, I'm going to notify the users a portion of the funds needs to remain in the balance as long as channels are active. If they need the Savings Balance funds, they might need to close all of their channels before fully withdrawing their Saving Balance.  Also I will tell them we are working on enabling a way for them to remove their funds while living the necessary portion for their channels to remain open. but for the moment  it is an all or nothing .

**Comment by jpl-btc** [comment]
![image](https://github.com/user-attachments/assets/9b3e8cef-9979-4be0-ba11-27757ad57ce8)
Here is a Hub having that issue and no online channels
