### ISSUE TITLE
Add high fee warning when opening or closing a channel, or withdrawing/depositing onchain funds

### ISSUE THREAD

**Issue by rolznz** [getAlby/hub#533]
If the mempool fees are higher than normal, show a warning (both on the first channel page and the manual flows)

**Comment by jpl-btc** [comment]
idea, tilting little text and small warning icon before the topup/increase buttons
![image](https://github.com/user-attachments/assets/2682d8f7-e7c9-4121-b5f4-a3852c326c40)

**Comment by bumi** [comment]
👍 we should do that on the page where one opens the channel. imo we don't want to make this page complicated with warnings that are most of the time irrelevant when visiting that page.
