### ISSUE TITLE
Alby shared balance migration card follow up tasks

### ISSUE THREAD

**Issue by rolznz** [getAlby/hub#567]
From https://github.com/getAlby/hub/pull/555

- Update the icon as the user is not "moving away from Alby" - they are just taking custody of funds.
- Update copy: "still hosted by Alby" -> "still on your Alby shared wallet."
- Remove onboarding slide because it is irrelevant to users who do not have shared funds
- Use "Migrate" instead of "Transfer" on Node page

**Comment by stackingsaunter** [comment]
Let's maybe use this icon

https://lucide.dev/icons/arrow-right-left.

How about we use "alert" component with added button? Like this:

![image](https://github.com/user-attachments/assets/41170360-f805-4514-8c45-b58606dfa7de)

**Comment by rolznz** [comment]
- For now, just update the icon and copy. Do not do redesign.
