### ISSUE TITLE
Warn against opening a mix of private and public channels

### ISSUE THREAD

**Issue by rolznz** [getAlby/hub#58]
For new lightning node runners there are some caveats and most likely they will not like the outcome. We can warn against this preemptively at the time they decide to open a channel.

**Comment by rolznz** [comment]
I talked about this with @bumi - it does not solve the root issue. The user shouldn't even hit this in the first place.

> + let's do some paper prototyping and think experiment with different ideas on how it can look like and present it to those users in a user test
> + do step-by-step guides for podcasters and others
> + create a podcast landing page that tells the user how to set things up as a podcast and what to care about
> + the landing pages is something that we might also want for the uncle jim, or other use cases

**Comment by jpl-btc** [comment]
This issue keeps recurring. Some users click the "public" option once but don’t do it consistently, ending up with a private channel that can’t receive payments. Meanwhile, the public channel they created needs time to properly broadcast across the network. This user had the mixed feeling of having two big channels, and no capability to receive sats right after the user created those channels and spent lots of sats on that.

Possibly this bad user experience could be avoided by some additional ui/ux mechanism.
Would it be possible to add a switch under "advanced" that defaults to off, but when turned on, only allows public channels to be created? Also, once a channel is opened, the switch would be locked to prevent users from creating a channel type different from what they have open already.

![image](https://github.com/user-attachments/assets/c0c18085-7fe5-4a31-b497-daf6f8287256)

**Comment by rolznz** [comment]
I think at the least we could show an alert on the node page after a user has done this, so a user knows that something is wrong.
