### ISSUE TITLE
Show Channel Reserves in the UI

### ISSUE THREAD

**Issue by rolznz** [getAlby/hub#59]
1. Get 1M sat channel opened *to you* (from LSP or ask someone to open a channel to you)
2. Deposit 6000 sats
3. Balance still shows 0 (6000/10000 in channel reserve).

![image](https://github.com/getAlby/nostr-wallet-connect-next/assets/33993199/cff160ed-17e5-4170-99d9-1896d071c4b6)

@reneaaron do you have an idea for a nice UX for this?

**Comment by reneaaron** [comment]
This has been added to the channel list.
