### ISSUE TITLE
Show lightning address in the Hub

### ISSUE THREAD

**Issue by MoritzKa** [getAlby/hub#595]
Currently we only show it on the "Connection" screen and don't mention that it is the lightning address. 

Can we show the address somewhere else where it is easily visible/accessible? For instance around the personal icon in the bottom left corner?

Let's keep in mind that only Alby account users have a lightning address, in case Alby accounts are optional.

**Comment by rolznz** [comment]
Maybe we can do a first implementation and then it can be iterated on
