### ISSUE TITLE
Automate unlocking of Hubs

### ISSUE THREAD

**Issue by MoritzKa** [getAlby/hub#596]
1) Users don't know the pattern of unlocking an app in order to send/receive based on our observations. 

2) In Alby Hub the problem is worse because users interact often in 3rd party apps instead of the Hub directly. This would require them to leave the app, find their Hub, unlock it and return to the app. Imagine you do that while paying for a coffee and behind you is a queue of people.  :-)

**Comment by rolznz** [comment]
Related: https://github.com/getAlby/hub/pull/592

This cannot be done in Alby Cloud though.

**Comment by MoritzKa** [comment]
Oh sorry. I did not check previous issue. I'll close it then?

**Comment by bumi** [comment]
You can not automate that, the password is used to encrypt things. I don't want to give you my password to decrypt things, then the whole encryption is usless.

**Comment by rolznz** [comment]
This works now, for self-hosted hubs
