### ISSUE TITLE
Reinstalling / updating causes a double entry in albyhub.service

### ISSUE THREAD

**Issue by tidley** [getAlby/hub#609]
Albyhub service had a config error after re-running the Linux installation script [here](https://github.com/getAlby/hub/tree/master/scripts/linux-x86_64#alby-hub-on-a-linux-server) caused by the albyhub.service written twice.

**Comment by bumi** [comment]
I think this is now fixed by just removing the `-a` . can you try again?

**Comment by tidley** [comment]
Yes it works - I amended the pull request with your suggestion https://github.com/getAlby/hub/pull/610/files

**Comment by rolznz** [comment]
Closed by https://github.com/getAlby/hub/pull/610
