### ISSUE TITLE
Bug: Doubled incoming balance after closing channel (LDK)

### ISSUE THREAD

**Issue by rolznz** [getAlby/hub#612]
![image](https://github.com/user-attachments/assets/53cdc546-6d54-4844-bf42-23e173e42579)

**Comment by jpl-btc** [comment]
This had a follow up -> The visualization bug part 2:
Finally those funds were settled and are in my Savings Balance.
However, it seems The Pending Closed Channels notification, continue to be there, and there is a ghost sum of exactly half of what appeared before on the incomings sats small grey section of the Savings Balance box.
![image](https://github.com/user-attachments/assets/c478fdd3-6d0c-483e-991e-12bd1260f8a2)

**Comment by jpl-btc** [comment]
Part 3: After some blocks confirmations, the problems of part 2 disappeared. And now everything is as it should be.
![image](https://github.com/user-attachments/assets/4c714553-84f9-45e7-bb67-57cc6d304e51)

**Comment by rolznz** [comment]
There is probably some overlap in `LightningBalances` and `PendingBalancesFromChannelClosures` https://github.com/getAlby/hub/blob/master/lnclient/ldk/ldk.go#L1000

If so, we could check the channel ID to ensure the balance from the same channel is not added twice

**Comment by jpl-btc** [comment]
If this happens again I'll record it

**Comment by rolznz** [comment]
This is worse than I thought because if the closing channel TX is not bumped, this could stay showing the wrong amount for many hours
