### ISSUE TITLE
Small copy improvement in Family and Friends app

### ISSUE THREAD

**Issue by MoritzKa** [getAlby/hub#623]
What about we name the options

- Alby Go Mobile App
- Alby Web Account
- Alby Browser Extension
- ...

(at least the Alby Browser Extension would be more clear)

![image](https://github.com/user-attachments/assets/fa366ac9-9567-4ede-bc23-ffcde04e1542)

**Comment by rolznz** [comment]
The other changes were made by @bumi except "Alby Account" to "Alby Web Account". I don't think this is a good change actually, the Alby Account is not just about the web. @MoritzKa are you ok with this? I'll close the issue for now.
