### ISSUE TITLE
Config: do not overwrite DB entries from env variables to allow backup import

### ISSUE THREAD

**Issue by bumi** [getAlby/hub#624]
If configuration environment variables are set we always use those instead of the data in the DB. 
This is kinda important if env variables get changed. 

but this is a problem when as a user I want to manually overwrite those within the app for example with a node import. 
It is right now not possible to import a backup from a different backend than the one configured with the env variable. 

I am not sure what's best. Should we not overwrite what's in the database already?

https://github.com/getAlby/hub/blob/master/config/config.go#L39-L72

If we use `SetIgnore` the data is set once but if it's present in the DB then it's ignored. If a user wants to use the env variables then the data directory needs to be deleted.

**Comment by rolznz** [comment]
Fixed in https://github.com/getAlby/hub/pull/657
