### ISSUE TITLE
Receive always +0 Sats

### ISSUE THREAD

**Issue by pizzesser** [getAlby/hub#625]
Hi. 
Everytime if i receive a Payment in the Transaction Notification stays +0 Sats.

Setup: Alby Hub with Phoenixd on Umbrel

The sats are credited to the total balance, but in the transaction overview you always see +0 sats. When I send something, the correct number is shown.

The channel opening fee has long since been paid.
![Bildschirmfoto vom 2024-09-08 11-56-57](https://github.com/user-attachments/assets/370b3ed7-f2c4-4a61-b6ab-137f3f565f9a)

Thanks!

**Comment by bumi** [comment]
hi, this is fixed in the last version 1.7.3 
If you used the alby umbrel community store you should be able to update.

**Comment by pizzesser** [comment]
Thank you, now it works!
