### ISSUE TITLE
Improve Connect Alby Account page

### ISSUE THREAD

**Issue by rolznz** [getAlby/hub#642]
The illustration is irrelevant and the copy will probably not get read. How can we better showcase the best features of the Alby Account?

How can we show the benefits of the Alby Account on other pages too, without annoying the users who want to run without an account?

![image](https://github.com/user-attachments/assets/9406d224-b13a-4aa1-b1c9-ddacaa44b0e0)

**Comment by jpl-btc** [comment]
An Alby Account gives them a lightning address for free. That is the most interesting and always used feature. 

I believe focus should be made on that single feature, and the others can be shortly mentioned in a smaller, less focused list that includes:
- Customize their lightning address with a name of their choosing
- Having invite for other friends to have their free lightning address as well.
- Having automated emails that will let them know how many sats they receive, or if they have to do something about some particular channel on their Hub's node. In other words, email notifications that can be customized, and this is for free.
- Podcasters receive v4v tags easy to use and share on their social networks
- Maybe we could think on something that addresses business needs, like something about making easier currency conversions
- Developers get An API with tons of options and opportunities.

**Comment by rolznz** [comment]
Most of the original feedback was addressed in https://github.com/getAlby/hub/pull/701 although we will do further iterations. I'm not sure about a focus on the lightning address as we are thinking of adding a lite lightning address service soon. I wonder about the developer one (I like it but what about everyday users?)

**Comment by rolznz** [comment]
I'll mark this one closed as now

**Comment by rolznz** [comment]
New design:

![image](https://github.com/user-attachments/assets/bf11af85-17a1-41ac-9a46-c80af5506065)
