### ISSUE TITLE
Hub on Umbrel | Spending Balance discrepancy between Alby Hub and LND app

### ISSUE THREAD

**Issue by jpl-btc** [getAlby/hub#644]
There’s a discrepancy between the spending balance shown by Alby Hub on Umbrel and the LND node. While the LND node shows a fixed balance, the Alby Hub balance fluctuates by a few thousand sats daily. 

My theory, based on previous conversations about this on slack, is that this is likely due to dynamic channel reserve fees, which vary with on-chain fees. The LND node doesn’t display these reserve fees, causing the balances to differ.

**Comment by rolznz** [comment]
I also think we need to fix that the reserves show as part of the spending balance, that's completely wrong (you cannot spend reserves) CC @im-adithya
