### ISSUE TITLE
Issue: Misunderstanding of Seed Phrase Restoration Scope

### ISSUE THREAD

**Issue by jpl-btc** [getAlby/hub#645]
Some users believe the seed phrase will restore the entire Alby Hub status, including channel states. This misunderstanding has been observed among new users several times.

To prevent this, add a warning pop-up before the page where the seed phrase is copied. The pop-up should briefly explain what the seed can restore, what it cannot, and how users can recover channel funds in case of device or hub failure.

![image](https://github.com/user-attachments/assets/0fb0cf4a-50ff-40f9-a11c-95820ed5f796)

**Comment by rolznz** [comment]
We improved the copy a bit on this backup page, but I think we still need to link to the new guide that @reneaaron and @jpl-btc are working on.

**Comment by rolznz** [comment]
Edit: we should probably also include it on the advanced setup -> restore from seed page

**Comment by rolznz** [comment]
Guide: https://guides.getalby.com/user-guide/v/alby-account-and-browser-extension/alby-hub/backups
