### ISSUE TITLE
Unable to pay Primal invoice (with Cashu backend)

### ISSUE THREAD

**Issue by thebullishbitcoiner** [getAlby/hub#650]
I'm getting the following error when trying to send sats to a Primal address (e.g. thebullishbitcoiner@primal.net). 

![image](https://github.com/user-attachments/assets/4912634e-2ad7-4f1d-b409-b2d90fd7ab96)

**Comment by rolznz** [comment]
@thebullishbitcoiner which mint did you use?

**Comment by thebullishbitcoiner** [comment]
I used the Minibits mint.

**Comment by thebullishbitcoiner** [comment]
It wasn't working on Alby Go just now but I restarted the app and was able to send to the Primal address and also pay an invoice generated from that address too. Not sure if the success was due to restarting the app or updating to v1.4.2 (3).

I'll try again from the hub and report back.

**Comment by rolznz** [comment]
@thebullishbitcoiner thanks! I've made a fix here: https://github.com/getAlby/hub/pull/660
