### ISSUE TITLE
Simplify copy of deposit bitcoin flow

### ISSUE THREAD

**Issue by MoritzKa** [getAlby/hub#663]
Users wonder where the difference comes from
![image](https://github.com/user-attachments/assets/09593de1-d4da-408d-b3ea-4aa71bd53ae2)

What about we keep and add: 
`You currently have X (here: 0) sats. We recommend to deposit Y (here: 510,000) sats to open a channel. This amount includes cost for the channel opening and potential channel onchain reserves.`

We erase: Z (here: ~506,000) sats are missing to cover the cost....

**Comment by itstomekk** [comment]
+1, submitted PR if it makes it easier: 

https://github.com/getAlby/hub/pull/664
