### ISSUE TITLE
Add "withdraw" button to savings balance

### ISSUE THREAD

**Issue by stackingsaunter** [getAlby/hub#676]
It should open withdraw onchain page, placed there for easier access and increasing feeling of control of funds for users

![image](https://github.com/user-attachments/assets/f9236b33-f77b-416f-aa32-ea7682ffad60)

**Comment by im-adithya** [comment]
<img width="100%" alt="Screenshot 2024-09-25 at 10 42 13 AM" src="https://github.com/user-attachments/assets/a34cbf63-7e11-49c6-b4dd-3e7548666378">

@stackingsaunter, it looks ugly when there are four balance boxes, should we use icons?

**Comment by rolznz** [comment]
the hosted balance should be migrated, it's not planned to always show. Maybe this card can be displayed differently in a follow-up?

**Comment by rolznz** [comment]
EDIT: anyway in a few months we can remove that card.
