### ISSUE TITLE
Wails crash and display problems

### ISSUE THREAD

**Issue by hans-schmidt** [getAlby/hub#719]
While experimenting with AlbyHub on a few different platforms, I encountered some issues which are apparently known Wails problems.

1) On Ubuntu-22.04, albyhub crashes on startup unless you first do "sudo apt-get install libwebkit2gtk-4.0-37"

2) With graphics acceleration, doing that install allows albyhub to run, but it presents only a blank white screen. This can be fixed by preceding the albyhub launch with the command "export WEBKIT_DISABLE_DMABUF_RENDERER=1"

**Comment by rolznz** [comment]
@hans-schmidt I have not seen these particular issues reported so far, especially I would have expected Ubuntu to have the least problems. But maybe we could add a troubleshooting section to the Linux section at  https://guides.getalby.com/user-guide/alby-account-and-browser-extension/alby-hub/alby-hub-flavors/desktop CC @jpl-btc 

Also, if users do have issues I think we should recommend them to run the server version. It has no GUI so is much less likely to have issues.

**Comment by jpl-btc** [comment]
Added to our guides 👍
![image](https://github.com/user-attachments/assets/eb983101-e350-4c97-95a2-1157ffa5edbd)
