### ISSUE TITLE
Missing feature: add a way to remove previous installation unlock password on desktop (windows)

### ISSUE THREAD

**Issue by jpl-btc** [getAlby/hub#734]
Last month, I installed the self-hosted Alby Hub on my Windows 10 desktop. I used it, tested it, and then removed it by erasing the unzipped folder with Alby Hub files in it.

Today, I re-downloaded the app and unzipped the files of this new downloaded Alby Hub to a new directory. When I double clicked on the .exe file, I expected to create a new unlock password, but to my surprise, Windows somehow "remembers" that I had a Hub before with a previous password and the brand new downloaded file of Alby Hub for windows is asking me for an unlock password that was set up last month with an already erased Alby Hub, and I can't find a way to reset or erase this password from Windows 10 in order to start a brand new Hub for desktop installation.

![image](https://github.com/user-attachments/assets/ca40c9fe-8f50-41ac-879a-d9c6d6556345)

**Comment by rolznz** [comment]
This is intentional for this very reason (so the user doesn't accidentally delete it, and have to copy files around when they update). Maybe we just need a guide for how a user can find the Alby Hub working directory.

We use the `XDG_DATA_HOME/albyhub` directory (see https://github.com/adrg/xdg)

**Comment by jpl-btc** [comment]
So in windows,  XDG_DATA_HOME	-> %LOCALAPPDATA% -> C:\Users\<YourUsername>\AppData\Local
I found it. I'm not sure if it is worth doing a guide right now, it's enough knowing where it is. I have not heard of users requiring this so far, only myself.
![image](https://github.com/user-attachments/assets/b1b4c2db-54eb-45a7-b129-0ef1dfb07cae)

**Comment by rolznz** [comment]
@jpl-btc actually, could you add it to this guide? https://guides.getalby.com/user-guide/alby-account-and-browser-extension/alby-hub/backups

It would be good for users who do not connect their Alby Account to know how to find their data directory to back it up.

**Comment by jpl-btc** [comment]
Done.
Info added to  https://guides.getalby.com/user-guide/alby-account-and-browser-extension/alby-hub/backups
![image](https://github.com/user-attachments/assets/be313def-3fb3-4ece-b61f-3cdbd92f63b9)

**Comment by rolznz** [comment]
@jpl-btc thanks. But it would be also good to have this for mac and linux too. Maybe there could be a section which explains where the work directory is, based on your operating system?

**Comment by jpl-btc** [comment]
Added short paragraph, thought I can't really verify it since I don't have a macOS
