### ISSUE TITLE
Can't fill reserve

### ISSUE THREAD

**Issue by rickykresslein** [getAlby/hub#758]
I'm having trouble in my Alby Hub filling the reserve balance of my original node (the first one I set up when I set up Alby Hub). I think this may be causing some issues I'm having with sending and receiving. I've thought about just deleting it, but since I paid to set it up I'd rather not. I've tried just sending myself sats, but it went to the other "Olympus" node rather than the reserve. Anything I can do? 

![alby-hub-reserve](https://github.com/user-attachments/assets/8f855625-e5b1-424a-b3d2-39dfb38e7ff5)

**Comment by rolznz** [comment]
Hi @rickykresslein there is no issue. What route a payment is received on depends on what route the node paying you chooses to take. It may be that the Olympus node has the least fees and still has a lot of receiving capacity, so you will more likely receive payments on that channel.

Your setup looks good.

**Comment by rickykresslein** [comment]
Oh, okay, thank you @rolznz, I appreciate the info.
