### ISSUE TITLE
Increase timeout for GetChannelPeerSuggestions

### ISSUE THREAD

**Issue by jontyms** [getAlby/hub#770]
https://github.com/getAlby/hub/blob/731d2481294bc8fbc5c637490f7c0c9e3a3a79fd/alby/alby_oauth_service.go#L921C1-L930C3 

This api call is taking about 25 seconds consistently.

**Comment by rolznz** [comment]
@jontyms thanks for reporting. We'll fix the slowdown on the Alby API side, this call should take way less than 10 seconds.
