### ISSUE TITLE
25k sats just vanished from my Alby Hub node

### ISSUE THREAD

**Issue by felipebueno** [getAlby/hub#817]
It looks like the Megalith LSP node is offline.

![image](https://github.com/user-attachments/assets/276ca8a0-7317-402f-84c5-d0fa423e71c2)

What to do in this situation?

I created a post on stacker news about that:

https://stacker.news/items/777271

**Comment by felipebueno** [comment]
My sats are back :)

![image](https://github.com/user-attachments/assets/4c31a625-d260-43e5-a8f6-681f5b1edbc9)

Not sure what happened, though

Not sure if I should close this issue, also

**Comment by jpl-btc** [comment]
Megalith had some issues, they fixed them, they are awesome, if this happens again best course of action is to wait, have patience, do not close anything, and you can reach our support at getalby.com/help

Best,
JP

**Comment by rolznz** [comment]
We need to find somewhere in Alby Hub to display a recommendation to open 2+ channels (apart from the node health indicator?).

**Comment by jpl-btc** [comment]
But we do not want to overwhelm the user that just arrived. Perhaps we could write some recommendations text, very short, to be shown after the first initial steps.

**Comment by rolznz** [comment]
I think some gamification / achievements could be cool here.
