### ISSUE TITLE
Update icons and order of sidebar items

### ISSUE THREAD

**Issue by stackingsaunter** [getAlby/hub#846]
Some icons and order of pages in the sidebar differ from design

![image](https://github.com/user-attachments/assets/a0d79d1d-34b1-4881-abbb-0ee3b12c8da6)

[Figma ](https://www.figma.com/design/2IyilDewDrdNP3G1NixPYd/%F0%9F%8C%93-Alby-Hub?node-id=449-46544&t=VWHiKnXopwk2fygG-4)

**Comment by rolznz** [comment]
I already updated the top ones, but the bottom ones need to be checked/re-ordered
