### ISSUE TITLE
albyhub docker start fails with exec err 255

### ISSUE THREAD

**Issue by kja999** [getAlby/hub#853]
I can no longer start the albyhub container, always with the below error
Running on pi5, 
uname -a 
Linux btcpi5 6.6.62+rpt-rpi-2712 #1 SMP PREEMPT Debian 1:6.6.62-1+rpt1 (2024-11-25) aarch64 GNU/Linux

# sudo docker compose --verbose up

TRAC[0000] Docker Desktop integration not enabled       
[+] Running 1/0
 ✔ Container albyhub  Created                                                                                                                                              0.0s 
Attaching to albyhub
albyhub  | exec /bin/main: exec format error
albyhub exited with code 255
DEBU[0000] otel error                                    error="<nil>"
DEBU[0000] otel error                                    error="<nil>"

I have tried reverting to older images but the error remains the same

**Comment by rolznz** [comment]
Hi, it looks like the executable is wrong for your architecture, which is weird, since docker build supports arm64. 

What command do you use to run it? and it used to work?

**Comment by rolznz** [comment]
What backend are you using, is this Phoenix?

**Comment by kja999** [comment]
Hey,
The prompt for the command was good. Found when I first ran it and setup, I used a docker run command, and not the compose. 
The default compose file had a platform entry I hadn't noticed so forced amd64.
