### ISSUE TITLE
Can't change relay on an existing alby hub installation in docker

### ISSUE THREAD

**Issue by riccardobl** [getAlby/hub#862]
I've been using alby hub with docker using the default relay.getalby.com relay.
However now i'd like to change it to use my own relay, but if i recreate the container with the `RELAY` env variable set
```console
$ docker run \
-d \
--name="albyhub" \
--restart=always \
-v/srv/albyhub:/data \
-eWORK_DIR='/data' \
-eRELAY="wss://nostr.rblb.it:7777" \
-p5241:8080 \
--pull always ghcr.io/getalby/hub:latest
```
the containers gets it
```console
$ docker exec -it albyhub bash -c "echo \$RELAY"
wss://nostr.rblb.it:7777
```

but alby hub still ends up using relay.getalby.com

```console
$ docker logs albyhub|grep relay
time="2024-12-08T12:57:15Z" level=info msg="AlbyHub Starting in HTTP mode"
{"iteration":0,"level":"info","msg":"Connecting to the relay","relay_url":"wss://relay.getalby.com/v1","time":"2024-12-08T12:57:23Z"}
{"level":"info","msg":"Connected to the relay","relay_url":"wss://relay.getalby.com/v1","time":"2024-12-08T12:57:27Z"}
````

**Comment by bumi** [comment]
If the relay_url is set in the nwc.db then it this will be taken. maybe the env variable should also be preferred here. 

to work around this for now you can remove the relay_url entry from the user_configs in the sqlite db.

**Comment by riccardobl** [comment]
thank you, i've used this workaround and got it running on my relay
