### ISSUE TITLE
The app freezes when I open a new channel

### ISSUE THREAD

**Issue by felipebueno** [getAlby/hub#876]
Alby Hub for linux v1.11.2

I'm on an Ubuntu 22.04 based distro

![image](https://github.com/user-attachments/assets/0b114fb3-00ef-4fdc-b660-247a97100e1d)

![image](https://github.com/user-attachments/assets/ae7355e0-ee36-4014-8666-73be0b395688)

![image](https://github.com/user-attachments/assets/c3873329-76b7-4c41-91aa-a2edaf156797)

![image](https://github.com/user-attachments/assets/da9c8a3f-b3ca-47ca-808f-6c07d03165b4)

**Comment by rolznz** [comment]
Could you open browser dev tools when this happens and see if you have any errors in the console?

Maybe we should remove this animation. It is a bit wacky anyway. I don't think it part of the official design, CC @stackingsaunter

**Comment by felipebueno** [comment]
> Could you open browser dev tools when this happens and see if you have any errors in the console?

I'm using the Linux desktop version of the app. How do I open the browser devtools on the desktop app?

![image](https://github.com/user-attachments/assets/8b2a3667-bda1-46dc-bf9c-8990c4d7aa95)

**Comment by stackingsaunter** [comment]
@rolznz feel free to delete

**Comment by rolznz** [comment]
@felipebueno thanks for reporting. We'll remove the confetti in the next minor version.
