### ISSUE TITLE
How to delete old settings Alby Hub ?

### ISSUE THREAD

**Issue by EdoardoSnodato** [getAlby/hub#921]
I would like to delete old settings Alby Hub, to have initialzation first, to connect my new Phoenixd

**Comment by rolznz** [comment]
Hi, where do you host alby hub? you can see where the data is stored for different operating systems here: https://guides.getalby.com/user-guide/alby-account-and-browser-extension/alby-hub/backups-and-recover#backup-checklist

**Comment by EdoardoSnodato** [comment]
> Hi, where do you host alby hub? you can see where the data is stored for different operating systems here: https://guides.getalby.com/user-guide/alby-account-and-browser-extension/alby-hub/backups-and-recover#backup-checklist

Thanks for support
I solved, erased folder /home/user/.local/share

Happy sats

**Comment by EdoardoSnodato** [comment]
> > Hi, where do you host alby hub? you can see where the data is stored for different operating systems here: https://guides.getalby.com/user-guide/alby-account-and-browser-extension/alby-hub/backups-and-recover#backup-checklist
> 
> Thanks for support
> I solved, deleted folder /home/user/.local/share/albyhub
> 
> Happy sats

**Comment by EdoardoSnodato** [comment]
> > Hi, where do you host alby hub? you can see where the data is stored for different operating systems here: https://guides.getalby.com/user-guide/alby-account-and-browser-extension/alby-hub/backups-and-recover#backup-checklist
> 
> Thanks for support
> I solved, deleted folder /home/user/.local/share/albyhub
> 
> Happy sats
